-   id: branch-name-validator-hook
    name: Branch Name Validator Hook
    description: Ensure branches have given names or match a pattern.
    entry: branch-name-validator-hook
    language: python
    always_run: true
    stages: [pre-commit, pre-merge-commit, pre-push, manual]
-   id: python-docstring-checker
    name: Python Docstring Checker Hook
    description: Check custom Python functions for docstrings.
    entry: docstring-checker
    language: python
    always_run: true
    stages: [pre-commit, pre-merge-commit, pre-push, manual]